### ISSUE TITLE
Exception You cannot define a correlation name

### ISSUE THREAD

**Issue by leandrosunrise** [dotmailer/dotmailer-magento2-extension#309]
1.  Magento 2.1.6
2. PHP 7.0.15
### Workaround 

for now I comment this out
``` 
<preference for="Magento\SalesRule\Model\ResourceModel\Coupon" type="Dotdigitalgroup\Email\Model\SalesRule\Coupon"/>
<preference for="Magento\SalesRule\Model\ResourceModel\Rule\Collection" type="Dotdigitalgroup\Email\Model\SalesRule\Collection"/>
```
This error usually happens because of a join with a similar alias.
Also, avoid rewriting magento core classes the preference node has been design to allow developers the use  of design by contract style programming in their modules. e.g.  You should use the preference node to enforce the use of interfaces in your module.

### Steps to reproduce
We have a large amount of coupon codes I haven't it tested without with a small amount.
Create a coupon with a specific code.
Try to use coupon code on front-end

### Expected result
1. Coupon code should should be applied.

### Actual result
```[2017-05-24 05:15:25] main.CRITICAL: exception 'Zend_Db_Select_Exception' with message 'You cannot define a correlation name 'rule_coupons' more than once' in /var/www/development.smokingvapor.com/public_html/vendor/magento/zendframework1/library/Zend/Db/Select.php:810
Stack trace:
#0 /var/www/public_html/vendor/magento/framework/DB/Select.php(298): Zend_Db_Select->_join('left join', Array, 'main_table.rule...', Array, NULL)
#1 /var/www/public_html/vendor/magento/zendframework1/library/Zend/Db/Select.php(359): Magento\Framework\DB\Select->_join('left join', Array, 'main_table.rule...', Array, NULL)
#2 /var/www/public_html/app/code/Dotdigitalgroup/Email/Model/SalesRule/Collection.php(51): Zend_Db_Select->joinLeft(Array, 'main_table.rule...', Array)
#3 /var/www/public_html/vendor/magento/module-sales-rule/Model/Validator.php(179): Dotdigitalgroup\Email\Model\SalesRule\Collection->setValidationFilter('1', '0', 'leandro', NULL, Object(Magento\Quote\Model\Quote\Address\Interceptor))
#4 /var/www/public_html/vendor/magento/module-offline-shipping/Model/SalesRule/Calculator.php(31): Magento\SalesRule\Model\Validator->_getRules(Object(Magento\Quote\Model\Quote\Address\Interceptor))
#5 /var/www/public_html/vendor/magento/module-offline-shipping/Model/Quote/Address/FreeShipping.php(65): Magento\OfflineShipping\Model\SalesRule\Calculator->processFreeShipping(Object(Magento\Quote\Model\Quote\Item))
#6 /var/www/public_html/vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php(63): Magento\OfflineShipping\Model\Quote\Address\FreeShipping->isFreeShipping(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#7 /var/www/public_html/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(265): Magento\Quote\Model\Quote\Address\Total\Shipping->collect(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\ShippingAssignment), Object(Magento\Quote\Model\Quote\Address\Total))
#8 /var/www/public_html/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(144): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#9 /var/www/public_html/vendor/magento/module-quote/Model/Quote.php(1923): Magento\Quote\Model\Quote\TotalsCollector->collect(Object(Magento\Quote\Model\Quote\Interceptor))
#10 /var/www/public_html/vendor/magento/module-checkout/Controller/Cart/CouponPost.php(84): Magento\Quote\Model\Quote->collectTotals()
#11 /var/www/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Checkout\Controller\Cart\CouponPost->execute()
#12 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Checkout\Controller\Cart\CouponPost\Interceptor->___callParent('dispatch', Array)
#14 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Array, 'storeCheck')
#15 /var/www/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Array, 'contextPlugin')
#18 /var/www/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Array, 'customer-app-ac...')
#21 /var/www/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Array, 'weee-app-action...')
#24 /var/www/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Array, 'tax-app-action-...')
#27 /var/www/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Checkout\Controller\Cart\CouponPost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\CouponPost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/public_html/var/generation/Magento/Checkout/Controller/Cart/CouponPost/Interceptor.php(26): Magento\Checkout\Controller\Cart\CouponPost\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /var/www/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Checkout\Controller\Cart\CouponPost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#33 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#34 /var/www/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#37 /var/www/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#40 /var/www/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /var/www/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#43 /var/www/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /var/www/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /var/www/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#46 /var/www/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /var/www/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#48 /var/www/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#49 {main} [] []

**Comment by cdiacon** [comment]
thanks @leandrosunrise  for this, also I have found the related issue https://github.com/dotmailer/dotmailer-magento2-extension/commit/54f8c9b6501c4e2d52469a7a6a7b88382bf6d29e#diff-dd609b3c539c55d5b5e50089eeb10f3d which is already on master

you should not use "testing branch" on production or bug reporting.
