### ISSUE TITLE
Dotmailer v2.4.5 breaks Design configuration page on Magento 2.1.10

### ISSUE THREAD

**Issue by zack6849** [dotmailer/dotmailer-magento2-extension#506]
Dotmailer v2.4.5 installed via composer on Magento 2.1.10

Accessing a store's design configuration page, (or, trying, rather) fails and th following ends up in the error reports

```
Warning: Illegal string offset 'template_text' in /home/revivaldev/www_magento2/staging/2018-03-12-072603/vendor/dotmailer/dotmailer-msion/Plugin/TemplatePlugin.php(74): Magento\Framework\App\ErrorHandler->handler(2, 'Illegal string ...', '/home/acme/mage...', 74, Array)


#0 /home/acme/magento2/staging/2018-03-12-072603/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TemplatePlugin.php(74): Magento\Framework\App\ErrorHandler->handler(2, 'Illegal string ...', '/home/acme/mage...', 74, Array)
#1 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(152): Dotdigitalgroup\Email\Plugin\TemplatePlugin->afterGetData(Object(Magento\Email\Model\Template\Interceptor), '1')
#2 /home/acme/magento2/staging/2018-03-12-072603/var/generation/Magento/Email/Model/Template/Interceptor.php(39): Magento\Email\Model\Template\Interceptor->___callPlugins('getData', Array, Array)
#3 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/DataObject.php(384): Magento\Email\Model\Template\Interceptor->getData('template_id', NULL)
#4 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-email/Model/Template.php(166): Magento\Framework\DataObject->__call('getTemplateId', Array)
#5 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Data/Collection.php(437): Magento\Email\Model\Template->getId()
#6 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Data/Collection/AbstractDb.php(171): Magento\Framework\Data\Collection->_getItemId(Object(Magento\Email\Model\Template\Interceptor))
#7 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Data/Collection.php(402): Magento\Framework\Data\Collection\AbstractDb->_getItemId(Object(Magento\Email\Model\Template\Interceptor))
#8 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Data/Collection/AbstractDb.php(582): Magento\Framework\Data\Collection->addItem(Object(Magento\Email\Model\Template\Interceptor))
#9 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#10 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-config/Model/Config/Source/Email/Template.php(53): Magento\Framework\Data\Collection\AbstractDb->load()
#11 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-ui/Component/Form/Element/AbstractOptionsField.php(52): Magento\Config\Model\Config\Source\Email\Template->toOptionArray()
#12 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-ui/Component/AbstractComponent.php(133): Magento\Ui\Component\Form\Element\AbstractOptionsField->prepare()
#13 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-ui/Component/Form/Field.php(96): Magento\Ui\Component\AbstractComponent->prepareChildComponent(Object(Magento\Ui\Component\Form\Element\Select))
#14 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Generator/UiComponent.php(148): Magento\Ui\Component\Form\Field->prepare()
#15 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Field))
#16 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Fieldset))
#17 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Fieldset))
#18 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Generator/UiComponent.php(126): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form))
#19 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'design_config_f...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#20 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#21 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#22 /home/acme/magento2/staging/2018-03-12-072603/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#23 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#24 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#25 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#26 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#27 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#28 /home/acme/magento2/staging/2018-03-12-072603/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#29 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#30 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-theme/Controller/Adminhtml/Design/Config/Edit.php(69): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Theme::...')
#31 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/App/Action/Action.php(102): Magento\Theme\Controller\Adminhtml\Design\Config\Edit->execute()
#32 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->___callParent('dispatch', Array)
#35 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Theme\\C...', 'dispatch', Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Array, 'adminAuthentica...')
#36 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Theme\\C...', 'dispatch', Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Array, 'adminMassaction...')
#39 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /home/acme/magento2/staging/2018-03-12-072603/var/generation/Magento/Theme/Controller/Adminhtml/Design/Config/Edit/Interceptor.php(26): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#42 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/App/FrontController.php(55): Magento\Theme\Controller\Adminhtml\Design\Config\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#45 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'm2epro_plugin_h...')
#46 /home/acme/magento2/staging/2018-03-12-072603/vendor/m2epro/magento2-extension/Plugin/HealthStatus/Magento/Framework/App/FrontController.php(79): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /home/acme/magento2/staging/2018-03-12-072603/vendor/m2epro/magento2-extension/Plugin/AbstractPlugin.php(43): Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->processDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Array)
#48 /home/acme/magento2/staging/2018-03-12-072603/vendor/m2epro/magento2-extension/Plugin/HealthStatus/Magento/Framework/App/FrontController.php(42): Ess\M2ePro\Plugin\AbstractPlugin->execute('dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Array)
#49 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Chain/Chain.php(67): Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#50 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#51 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#52 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#53 /home/acme/magento2/staging/2018-03-12-072603/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#54 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#55 /home/acme/magento2/staging/2018-03-12-072603/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#56 /home/acme/magento2/staging/2018-03-12-072603/pub/index.php(47): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#57 {main}

**Comment by cdiacon** [comment]
@zack6849 yes it's been fixed.

Thanks.
