### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by sunilit42** [dotmailer/dotmailer-magento2-extension#511]
Hello,

we added your module to cloud environment.
We are facing below error:-

[2018-05-25 13:23:16] report.CRITICAL: Exception message: Connection timed out
Trace: #0 /app/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php(167): Zend_Mail_Protocol_Abstract->_connect('tcp://r2-smtp.d...')
#1 /app/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php(199): Zend_Mail_Protocol_Smtp->connect()
#2 /app/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()

**Comment by adeelq** [comment]
@sunilit42 in module's config see which port is used. Try changing port to different port.

**Comment by mpchadwick** [comment]
Ran into the same issue. Switching from port 25 to port 2525 seems to have resolved it. If port 25 is not supported anymore should it not be removed here? https://github.com/dotmailer/dotmailer-magento2-extension/blob/e8335e87c008699b2669e870b8d2a68f5863223e/Model/Config/Source/Transactional/Port.php#L15
