### ISSUE TITLE
Error during setup:upgrade - version: 3.2.3

### ISSUE THREAD

**Issue by pioneerathletics** [dotmailer/dotmailer-magento2-extension#549]
Hi,

I'm running Magento version 2.1.17 and I manually update the Dotdigital email module. When trying to update to version 3.2.3, after running setup:upgrade I received this error:
```
Fatal error: Uncaught TypeError: Argument 1 passed to Dotdigitalgroup\Email\Setup\Install\Type\AbstractDataMigration::__construct() must be an instance of Magento\Framework\App\ResourceConnection, instance of Magento\Setup\Module\DataSetup given, called in /srv/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /srv/public_html/app/code/Dotdigitalgroup/Email/Setup/Install/Type/AbstractDataMigration.php:49
Stack trace:
#0 /srv/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Dotdigitalgroup\Email\Setup\Install\Type\AbstractDataMigration->__construct(Object(Magento\Setup\Module\DataSetup))
#1 /srv/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Dotdigitalgroup...', Array)
#2 /srv/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Dotdigitalgroup...')
# in /srv/public_html/app/code/Dotdigitalgroup/Email/Setup/Install/Type/AbstractDataMigration.php on line 49
```

**Comment by benathomeofchampions** [comment]
Hi,
Thanks for reporting this to us. 

We have investigated the issue, and been unable to recreate it our side. However, the constructor of that class was changed in a recent version, so it is likely you will need to recompile dependencies.

If possible, could you run `bin/magento setup:di:compile` and retry the upgrade?

**Comment by pioneerathletics** [comment]
Hi Ben,

 

I re-ran setup:di:compile and everything worked as expected. Thank you!

 

David Orzechowski

Pioneer Athletics | Marketing

800.877.1500 x3179

dorzechowski@pioneerathletics.com
