### ISSUE TITLE
Error Running Cron on Magento 2.4.4-p1 (v1.4.2 -> module version  4.18.2)

### ISSUE THREAD

**Issue by tschirmer** [dotmailer/dotmailer-magento2-extension#591]
```
[2022-09-12T00:42:24.075480+00:00] main.CRITICAL: TypeError: Dotdigitalgroup\Email\Model\Connector\Product::setProduct(): Argument #2 ($storeId) must be of type int, null given, called in /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Sync/Catalog/Exporter.php on line 60 and defined in /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Connector/Product.php:262
Stack trace:
#0 /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Sync/Catalog/Exporter.php(60): Dotdigitalgroup\Email\Model\Connector\Product->setProduct()
#1 /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Sync/Catalog/StoreCatalogSyncer.php(34): Dotdigitalgroup\Email\Model\Sync\Catalog\Exporter->exportCatalog()
#2 /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Sync/Catalog/DefaultLevelCatalogSyncer.php(64): Dotdigitalgroup\Email\Model\Sync\Catalog\StoreCatalogSyncer->syncByStore()
#3 /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Sync/Catalog.php(182): Dotdigitalgroup\Email\Model\Sync\Catalog\DefaultLevelCatalogSyncer->sync()
#4 /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Sync/Catalog.php(122): Dotdigitalgroup\Email\Model\Sync\Catalog->syncCatalog()
#5 /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Cron.php(209): Dotdigitalgroup\Email\Model\Sync\Catalog->sync()
#6 [internal function]: Dotdigitalgroup\Email\Model\Cron->catalogSync()
#7 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(368): call_user_func_array()
#8 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(879): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob()
#9 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(840): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob()
#10 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(280): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs()
#11 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver->execute()
#12 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#13 /var/www/html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#14 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#15 /var/www/html/vendor/magento/framework/App/Cron.php(86): Magento\Framework\Event\Manager\Proxy->dispatch()
#16 /var/www/html/vendor/magento/module-cron/Console/Command/CronCommand.php(117): Magento\Framework\App\Cron->launch()
#17 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Cron\Console\Command\CronCommand->execute()
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Console\Command\CronCommand\Interceptor->___callParent()
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Console\Command\CronCommand\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/html/generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php(23): Magento\Cron\Console\Command\CronCommand\Interceptor->___callPlugins()
#22 /var/www/html/vendor/symfony/console/Application.php(1009): Magento\Cron\Console\Command\CronCommand\Interceptor->run()
#23 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#24 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#25 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#26 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#27 {main}

Next RuntimeException: Error when running a cron job in /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:380
Stack trace:
#0 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(879): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob()
#1 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(840): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob()
#2 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(280): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs()
#3 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver->execute()
#4 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#5 /var/www/html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#6 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#7 /var/www/html/vendor/magento/framework/App/Cron.php(86): Magento\Framework\Event\Manager\Proxy->dispatch()
#8 /var/www/html/vendor/magento/module-cron/Console/Command/CronCommand.php(117): Magento\Framework\App\Cron->launch()
#9 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Cron\Console\Command\CronCommand->execute()
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Console\Command\CronCommand\Interceptor->___callParent()
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Console\Command\CronCommand\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php(23): Magento\Cron\Console\Command\CronCommand\Interceptor->___callPlugins()
#14 /var/www/html/vendor/symfony/console/Application.php(1009): Magento\Cron\Console\Command\CronCommand\Interceptor->run()
#15 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#16 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#17 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#18 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#19 {main} [] []
```

**Comment by pvpcookie** [comment]
Hi @tschirmer 

Thanks for bringing this to our attention, we are aware for the bug and have resolved it pending the 4.19.1 release coming up ( Most likely within the week ) [fix here](https://github.com/dotmailer/dotmailer-magento2-extension/blob/eadcd3785998b538058b05e57a782f89e0fdddde/Model/Connector/Product.php#L262).

We will let you know once 4.19.1 has been released / tagged, before we close the issue

**Comment by BrightDhiru** [comment]
Magento version 2.3.5  and I had installed this extension.
When I will upgrade Magento 2.4.5 then this will work proper or need to upgrade from your end.?

**Comment by pvpcookie** [comment]
HI @tschirmer

version[ 4.19.1](https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v4.19.1) has been released, please upgrade you extension to resolve the above mentioned issue.

**Comment by pvpcookie** [comment]
> Magento version 2.3.5 and I had installed this extension.
> When I will upgrade Magento 2.4.5 then this will work proper or need to upgrade from your end.?

Our extension currently supports magento version 2.4.5 if you use the latest release [ 4.19.1](https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v4.19.1) you should not have a problem when upgrading your magento to 2.4.5
